version: "3"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Nz9hpXgD_
    ports:
      - 1433:1433

  redis:
    image: redis

  app:
    build:
      context: .
      dockerfile: docker-conf/dockerfile-php73/dockerfile
    volumes:
      - ./:/var/www/html
      - ./docker-conf/.docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
      - ./docker-conf/docker-php-ext-extras.ini:/usr/local/etc/php/conf.d/docker-php-ext-extras.ini:ro
    working_dir: /var/www/html/src
    ports:
      - 8001:80
    links:
      - mssql
      - redis
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/src/public
